### ISSUE TITLE
Plotting routines for DecisionMaking problems

### ISSUE THREAD

**Issue by 00krishna** [algorithmsbooks/DecisionMakingProblems.jl#3]
Hello folks. I really appreciate the work that went into writing the ALGORITHMS FOR DECISION MAKING book. It is great that the authors included julia code as well as the algorithms for policy iteration, value iteration, SARSA, etc. 

My question is whether there is a place to find some plotting routines for these environments?

The biggest issue that I encounter in trying to run an understand these algorithms is that I have not found any suitable way to plot the policies that emerge from the learning process. So if I run some algorithm on a Gridworld problem, I would like to plot the policy on a Gridworld plot and then see the arrows indicating the policy. That would really help to understand whether the algorithm is converging and if the algorithm is implemented correctly. 

Is there anything like that available either in this repository--where the problems are defined--or in a different repo? Thanks.

**Comment by mykelk** [comment]
I think the plan (after we finish addressing copyedit feedback) is to post plotting code from the book in a separate repo, similar to what we did for Algorithms for Optimization. We want to keep this repo clean and focused on the problem definitions.

**Comment by 00krishna** [comment]
@mykelk Okay sounds good. Yeah, that is the biggest challenge that I find in exploring these models. To understand the algorithms it really helps to have the visualization tool. I am hoping that the JuliaReinforcementLearning.jl package will come along with some of this as well. Thanks for all of your work on the book and these repos.
